apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: {{ .Values.global.namespace }}
data:
  init.js: |
    db.getSiblingDB("admin").auth("root", "{{ .Values.database.auth.rootPassword }}");
    db = db.getSiblingDB("{{ .Values.database.auth.database }}");
    db.createUser({
      user: "{{ .Values.database.auth.username }}",
      pwd: "{{ .Values.database.auth.password }}",
      roles: [
        { role: "readWrite", db: "{{ .Values.database.auth.database }}" }
      ]
    });