apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.database.name }}
    tier: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: {{ .Values.database.name }}
    tier: database
  clusterIP: None