apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: multi-tier
  labels:
    app: mongodb
    tier: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
    tier: database
  clusterIP: None